apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-generator-blog
  namespace: openshift-gitops
spec:
  destination:
    namespace: policy-generator-blog
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize2
    repoURL: https://github.com/mihirlele/grc-policy-generator-blog.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=background
