apiVersion: v1                    
kind: Namespace
metadata:
  name: policy-generator-gitops-app                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: policy-generator-gitops-app
  namespace: policy-generator-gitops-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - policy-generator-gitops-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-mihirlele-grc-policy-generator-blog-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-mihirlele-grc-policy-generator-blog
  namespace: ggithubcom-mihirlele-grc-policy-generator-blog-ns
spec:
  type: Git
  pathname: 'https://github.com/mihirlele/grc-policy-generator-blog'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: kustomize
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policy-generator-gitops-app
  name: policy-generator-gitops-app-subscription-1
  namespace: policy-generator-gitops-app
spec:
  channel: ggithubcom-mihirlele-grc-policy-generator-blog-ns/ggithubcom-mihirlele-grc-policy-generator-blog
  placement:
    placementRef:
      kind: Placement
      name: policy-generator-gitops-app-placement-1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: policy-generator-gitops-app
  name: policy-generator-gitops-app-placement-1
  namespace: policy-generator-gitops-app
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'name'
              operator: 'In'
              values: 
                - 'local-cluster'
  clusterSets:
    - default
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: policy-generator-gitops-app
  name: default
spec:
  clusterSet: default
