apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-compliance-operator
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
  severity: medium
policies:
  - name: install-compliance-operator
    manifests:
      - path: compliance-operator
