apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  channel: release-1.6.1
  name: compliance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
