apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: spoke-placement
  name: spoke-placement-1
  namespace: acm-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'name'
              operator: 'NotIn'
              values: 
                - 'local-cluster'
  clusterSets:
    - default
